-- View: vw_your_custom_metric (vw_product_performance)
-- Purpose: Monitor product sales performance, unit counts, and revenue contribution
-- Business metric: Units sold, order occurrences, and total revenue per SKU
-- Updated: Automatically with each query (view recalculates)
-- Used by: Inventory managers, VP of Product, Sales team
-- 
-- Columns:
--   product_id: Unique product identifier
--   product_name: Display name of the product
--   order_count: Number of unique orders containing this product
--   total_units_sold: Aggregate quantity sold
--   total_revenue: Aggregate revenue generated by the product
--   avg_unit_price: Average price per unit sold

CREATE VIEW vw_your_custom_metric AS
SELECT 
    p.product_id,
    p.product_name,
    COUNT(DISTINCT o.order_id) as order_count,
    COALESCE(SUM(oi.quantity), 0) as total_units_sold,
    COALESCE(SUM(oi.quantity * oi.unit_price), 0) as total_revenue,
    ROUND(AVG(oi.unit_price), 2) as avg_unit_price
FROM products p
LEFT JOIN order_items oi ON p.product_id = oi.product_id
LEFT JOIN orders o ON oi.order_id = o.order_id
GROUP BY p.product_id, p.product_name;
